spring.application.name=Actionable

#h2 db config
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.driver
spring.datasource.username=username
spring.datasource.password=a_very_secure_password
spring.datasource.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
